CC=gcc
ABC:
	$(CC) ABC.c -o ABC.out
exec:
	$(CC) exec.c -o exec.out
fork:
	$(CC) fork.c -o fork.out
getpid:
	$(CC) getpid.c -o getpid.out
nwait:
	$(CC) nwait.c -o nwait.out
pfork:
	$(CC) pfork.c -o pfork.out
pipe:
	$(CC) pipe.c -o pipe.out
signal:
	$(CC) signal.c -o signal.out
wait:
	$(CC) wait.c -o wait.out
